[package]
name = "canvas-effect"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dependencies.anathema]
# path = "../../anathema"
git = "https://github.com/togglebyte/anathema.git"
branch = "dev"
